/**
 * Resuelve el taller número 1 del módulo 7 "Integración Módulos de Software",
 * Programa CORFO "Mil Programadores".
 *
 * @autor Daniel Zúñiga Correa, 2017-12-24 (yyyy-mm-dd)
 */
package vista;

import javax.swing.JOptionPane;
import modelo.*;

/**
 * Clase JFrame correspondiente a la vista que contiene principal del proyecto.
 *
 * @author Daniel Zúñiga Correa, 2017-12-24 (yyyy-mm-dd)
 */
public class Indicadores extends javax.swing.JFrame {
//    Declaración de variables de clase para su utilización en los métodos contenidos
//    en esta vista.

    public Indicador dolar;
    public Indicador utm;
    public Indicador uf;
    public Indicador euro;
    public Indicador ipc;

    private static final String url = "http://mindicador.cl/api/";
    public boolean problemasConexion = false;

    public Indicadores() {
        initComponents();
        this.setLocationRelativeTo(null);
//        Verifica que los indicadores esten disponibles en el url respectivo
        if (Metodos.urlConecta(url + "dolar")) {
            dolar = Metodos.consumirIndicador("dolar");
        } else {
            JOptionPane.showMessageDialog(null, "Error en la conexión a "
                    + url + "dolar\n");
            problemasConexion = true;
        }
        if (Metodos.urlConecta(url + "utm")) {
            utm = Metodos.consumirIndicador("utm");
        } else {
            JOptionPane.showMessageDialog(null, "Error en la conexión a "
                    + url + "utm\n");
            problemasConexion = true;
        }
        if (Metodos.urlConecta(url + "uf")) {
            uf = Metodos.consumirIndicador("uf");
        } else {
            JOptionPane.showMessageDialog(null, "Error en la conexión a "
                    + url + "uf\n");
            problemasConexion = true;
        }
        if (Metodos.urlConecta(url + "euro")) {
            euro = Metodos.consumirIndicador("euro");
        } else {
            JOptionPane.showMessageDialog(null, "Error en la conexión a "
                    + url + "euro\n");
            problemasConexion = true;
        }
        if (Metodos.urlConecta(url + "ipc")) {
            ipc = Metodos.consumirIndicador("ipc");
        } else {
            JOptionPane.showMessageDialog(null, "Error en la conexión a "
                    + url + "ipc\n");
            problemasConexion = true;
        }
        if (problemasConexion) {
            System.exit(0);
        }
        tbIndicadores.setModel(Metodos.llenarTabla(indicadorSeleccionado()));
        txaMenorVariacion.setText(indicadorSeleccionado().obtieneDiasMinimos());
        txaMayorVariacion.setText(indicadorSeleccionado().obtieneDiasMaximos());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbIndicadores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboIndicadores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaMenorVariacion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaMayorVariacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbIndicadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6 "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbIndicadores);
        if (tbIndicadores.getColumnModel().getColumnCount() > 0) {
            tbIndicadores.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbIndicadores.getColumnModel().getColumn(1).setPreferredWidth(70);
            tbIndicadores.getColumnModel().getColumn(2).setPreferredWidth(70);
            tbIndicadores.getColumnModel().getColumn(3).setPreferredWidth(40);
            tbIndicadores.getColumnModel().getColumn(4).setPreferredWidth(40);
            tbIndicadores.getColumnModel().getColumn(5).setPreferredWidth(70);
        }

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("INDICADORES");

        cboIndicadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar", "UTM", "UF", "Euro", "IPC" }));
        cboIndicadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIndicadoresActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Menor Variación");

        txaMenorVariacion.setColumns(20);
        txaMenorVariacion.setRows(5);
        jScrollPane2.setViewportView(txaMenorVariacion);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Mayor Variación");

        txaMayorVariacion.setColumns(20);
        txaMayorVariacion.setRows(5);
        jScrollPane3.setViewportView(txaMayorVariacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(69, 69, 69))))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboIndicadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboIndicadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboIndicadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIndicadoresActionPerformed
        tbIndicadores.setModel(Metodos.llenarTabla(indicadorSeleccionado()));
        txaMenorVariacion.setText(indicadorSeleccionado().obtieneDiasMinimos());
        txaMayorVariacion.setText(indicadorSeleccionado().obtieneDiasMaximos());

    }//GEN-LAST:event_cboIndicadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Indicadores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Indicadores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Indicadores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Indicadores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        new Indicadores().setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> cboIndicadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTable tbIndicadores;
    private javax.swing.JTextArea txaMayorVariacion;
    private javax.swing.JTextArea txaMenorVariacion;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para determinar cual objeto clase Indicador corresponde a la
     * opción seleccionada en el combo box respectivo
     *
     * @return retorna el objeto clase Indicador que corresponde a la opción
     * seleccionada en el combo box
     */
    private Indicador indicadorSeleccionado() {
        int index = cboIndicadores.getSelectedIndex();
        Indicador indicador = new Indicador();
        switch (index) {
            case 0:
                indicador = dolar;
                break;
            case 1:
                indicador = utm;
                break;
            case 2:
                indicador = uf;
                break;
            case 3:
                indicador = euro;
                break;
            case 4:
                indicador = ipc;
                break;
        }
        return indicador;
    }
}
